version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/react"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/vue"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/svelte"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/solid"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/wc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
